username: "magnuscarlsen"
base_url: "https://api.chess.com/pub/player"
archives_suburl: "games/archives"
raw_dir: "./data/raw"
clean_dir: "./data/clean"
ref_dir: "./data/ref"
openings_file: "openings_lut.csv"
all_archives: "False"

headers:
  User-Agent: "Mozilla/5.0"
  Accept: "application/json"
